name: Update Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every day
  push:
    branches:
      - main

jobs:
  update-contribution-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Generate contribution snake
        run: node generate-contribution-snake.js

      - name: Commit contribution snake
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add contribution-snake.svg
          git commit -m 'Update contribution snake'
          git push
